name: test-strapi

services:
- name: api
  build_command: NODE_ENV=production npm run build
  environment_slug: node-js
  github:
    branch: main    
    repo: felipebarcelospro/test-strapi
    deploy_on_push: true
  source_dir: api
  envs: 
    - NODE_ENV: production
  http_port: 1337
  routes:
  - path: /api

- name: frontend
  build_command: npm run build
  environment_slug: node-js
  github:
    branch: main
    deploy_on_push: true
    repo: felipebarcelospro/test-strapi
  source_dir: frontend
  routes:
  - path: /frontend